import { Router } from 'express';
import userRoutes from '../modules/user/user.routes.js';
import companyRoutes from '../modules/company/company.routes.js';
import departmentRoutes from '../modules/department/department.routes.js';
import roleRoutes from '../modules/role/role.routes.js';
import userEmploymentRoutes from '../modules/user_employment/user_employment.routes.js';
import permissionRoutes from '../modules/permission/permission.routes.js';
import rolePermissionRoutes from '../modules/role_permission/role_permission.routes.js';
import roleHandoverRuleRoutes from '../modules/role_handover_rule/role_handover_rule.routes.js';
import expenseCategoryRoutes from '../modules/expense_category/expense_category.routes.js';
import expenseRoutes from '../modules/expense/expense.routes.js';
import vendorRoutes from '../modules/vendor/vendor.routes.js';
import vendorDocumentRoutes from '../modules/vendor/vendor_document.routes.js';
import reimbursementRoutes from '../modules/reimbursement/reimbursement.routes.js';
import travelExpenseRoutes from '../modules/travel_expense/travel_expense.routes.js';
import travelSegmentRoutes from '../modules/travel_segment/travel_segment.routes.js';
import travelAccommodationRoutes from '../modules/travel_accommodation/travel_accommodation.routes.js';
import travelLocalTransportRoutes from '../modules/travel_local_transport/travel_local_transport.routes.js';
import travelForexRoutes from '../modules/travel_forex/travel_forex.routes.js';
import travelMiscExpenseRoutes from '../modules/travel_misc_expense/travel_misc_expense.routes.js';
import authRoutes from '../modules/auth/auth.routes.js';
import uploadRoutes from '../modules/upload/upload.routes.js';
import groupRoutes from '../modules/group/group.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/companies', companyRoutes);
router.use('/departments', departmentRoutes);
router.use('/roles', roleRoutes);
router.use('/user-employments', userEmploymentRoutes);
router.use('/permissions', permissionRoutes);
router.use('/role-permissions', rolePermissionRoutes);
router.use('/role-handover-rules', roleHandoverRuleRoutes);
router.use('/expense-categories', expenseCategoryRoutes);
router.use('/expenses', expenseRoutes);
router.use('/vendors', vendorRoutes);
router.use('/vendor-documents', vendorDocumentRoutes);
router.use('/reimbursements', reimbursementRoutes);
router.use('/travel-expenses', travelExpenseRoutes);
router.use('/travel-segments', travelSegmentRoutes);
router.use('/travel-accommodations', travelAccommodationRoutes);
router.use('/travel-local-transports', travelLocalTransportRoutes);
router.use('/travel-forex', travelForexRoutes);
router.use('/travel-misc-expenses', travelMiscExpenseRoutes);
router.use('/uploads', uploadRoutes);
router.use('/groups', groupRoutes);

export default router;
